function fdata = oft(tdata)
%OFT optimal Fourier transform
%   FDATA = OFT(TDATA) returns the FFT of the time domain signal TDATA
%   zero-padded such that the maximum amplitude response of the signal is
%   optimized.
%
%   For example, if an input time domain signal is a single-frequency
%   signal TDATA=SIN(2*PI*T), taking FFT(TDATA) may induce spectral leakage
%   which makes the amplitude response at 1 Hz appear less than it should.
%   This function will continually pad the time domain signal with zeros
%   until this spectral leakage is minimized.
%
%   This is designed for use with signals generated by the RITEC which are
%   supposed to be tone bursts at 2.1 and 4.2 MHz, but whose center
%   frequencies are often slightly off.
%
%   See also SFT, FFT
%
%   Written by Nick Selby Spring 2016

N = length(tdata);
% Find N which minimizes spectral leakage at largest amplitude
while max(abs(fft(tdata,N+1)/(N+1))) > max(abs(fft(tdata,N)/N))
    N = N+1;
end
fdata = fft(tdata,N);
end